START TRANSACTION;

ALTER TABLE "users" ADD COLUMN "accountId" VARCHAR(255) NOT NULL;
ALTER TABLE "users" ADD COLUMN "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ADD COLUMN "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

COMMIT;