// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package dao_user

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/stewie1520/elasticpmapi/tools/types"
)

type User struct {
	ID        uuid.UUID      `json:"id"`
	FullName  sql.NullString `json:"fullName"`
	AccountId string         `json:"accountId"`
	CreatedAt types.DateTime `json:"createdAt"`
	UpdatedAt types.DateTime `json:"updatedAt"`
}
