// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0
// source: user.query.sql

package dao_user

import (
	"context"

	"github.com/google/uuid"
)

const findUserById = `-- name: FindUserById :one
SELECT id, "fullName" FROM "users" WHERE "users"."id" = $1 LIMIT 1
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserById, id)
	var i User
	err := row.Scan(&i.ID, &i.FullName)
	return i, err
}
